/*
 * File: app/store/Contestants.js
 * Date: Tue Jan 24 2012 12:07:44 GMT-0600 (CST)
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('MyApp.store.Contestants', {
    extend: 'MyApp.store.base.Contestants',

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({}, cfg)]);
    }

});