/*
 * File: app/view/ContestantPanel.js
 * Date: Mon Jan 23 2012 14:43:41 GMT-0600 (CST)
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('MyApp.view.ContestantPanel', {
    extend: 'MyApp.view.ui.ContestantPanel',
    alias: 'widget.contestants'

});