/*
 * File: app/view/Main.js
 * Date: Tue Jan 24 2012 11:13:58 GMT-0600 (CST)
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('MyApp.view.Main', {
    extend: 'MyApp.view.ui.Main',

});