/*
 * File: app/view/PrizePanel.js
 * Date: Mon Jan 23 2012 16:58:34 GMT-0600 (CST)
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('MyApp.view.PrizePanel', {
    extend: 'MyApp.view.ui.PrizePanel',
    alias: 'widget.prizes'

});