/*
 * File: app/view/Viewport.js
 * Date: Mon Jan 23 2012 14:43:41 GMT-0600 (CST)
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you save.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Viewport', {
    extend: 'MyApp.view.Main',
    config: {
        fullscreen: true
    },
    requires: [
        'MyApp.view.Main'
    ]
});