/*
 * File: app/model/Contestant.js
 * Date: Mon Jan 23 2012 16:05:43 GMT-0600 (CST)
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you save.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.Contestant', {
    extend: 'Ext.data.Model',
    config: {
        clientIdProperty: 'id',
        fields: [
            {
                name: 'Name',
                type: 'string'
            },
            {
                name: 'id',
                type: 'int'
            }
        ]
    }
});