/*
 * File: app/view/ui/ContestantPanel.js
 * Date: Mon Jan 23 2012 17:08:07 GMT-0600 (CST)
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you save.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ui.ContestantPanel', {
    extend: 'Ext.Container',

    config: {
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'list',
                store: 'Contestants'
            },
            {
                xtype: 'toolbar',
                docked: 'top',
                items: [
                    {
                        xtype: 'button',
                        itemId: 'addContestant',
                        ui: 'action',
                        text: 'Add Contestant'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        itemId: 'callWinner',
                        ui: 'confirm',
                        text: 'Call Winner'
                    },
                    {
                        xtype: 'button',
                        itemId: 'clearContestants',
                        ui: 'decline',
                        text: 'Clear'
                    }
                ]
            }
        ]
    }

});