/*
 * File: designer.js
 * Date: Tue Jan 24 2012 15:04:34 GMT-0600 (CST)
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you save.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
    enabled: true
});

Ext.application({
    models: [
        'Contestant',
        'Prize'
    ],

    stores: [
        'Contestants',
        'Prizes'
    ],

    views: [
        'ContestantPanel',
        'PrizePanel'
    ],

    name: 'MyApp',

    controllers: [
        'Contestant',
        'Prize'
    ],

    launch: function() {
        Ext.create('MyApp.view.Viewport');
    }
});
