/*
 * File: app/store/base/Contestants.js
 * Date: Mon Jan 23 2012 12:27:27 GMT-0600 (CST)
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you save.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.base.Contestants', {
    extend: 'Ext.data.Store',
    requires: [
        'MyApp.model.Contestant'
    ],

    config: {
        autoLoad: true,
        autoSync: true,
        clearOnPageLoad: false,
        model: 'MyApp.model.Contestant',
        storeId: 'Contestants',
        proxy: {
            type: 'localstorage',
            reader: {
                type: 'json'
            }
        }
    }
});