/*
 * File: app/controller/Prize.js
 * Date: Mon Jan 23 2012 16:52:36 GMT-0600 (CST)
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('MyApp.controller.Prize', {
    extend: 'Ext.app.Controller',

    config: {
        stores: [
            'Prizes'
        ],
        control: {
            "prizes button[ui=action]": {
                tap: 'addPrize'
            },
            "prizes button[ui=decline]": {
                tap: 'clearPrizes'
            }
        }
    },

    addPrize: function(button, e, options) {
        var me = this;

        Ext.Msg.prompt(
        'Enter your Prize',
        'Enter the name of the prize.',
        function(btn, name) {
            if (btn === 'cancel') { return false; }

            if (!name || typeof name !== 'string' || name === '') { return false; }

            var newPrize = new MyApp.model.Prize({
                Name: name
            });

            var prizeStore = Ext.StoreMgr.lookup('Prizes');

            prizeStore.add(newPrize);
            prizeStore.sync();
        }
        );
    },

    clearPrizes: function(button, e, options) {
        var prizeStore = Ext.StoreMgr.lookup('Prizes');

        prizeStore.removeAll();
        prizeStore.getProxy().clear();
    }

});